# Generated by Django 5.2.4 on 2025-07-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notebook',
            table='notebook',
        ),
        migrations.AlterModelTable(
            name='notebookcollaborator',
            table='notebook_collaborator',
        ),
    ]
